# Generated by Django 4.2.19 on 2025-04-12 22:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_order_alter_basket_options_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Состав'),
            preserve_default=False,
        ),
    ]
