# Generated by Django 4.2.19 on 2025-04-14 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['name'], 'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'},
        ),
    ]
